### ISSUE TITLE
CP::TPileupReweighting crash

### ISSUE THREAD

**Issue by vpascuzz** [UCATLAS/xAODAnaHelpers#1214]
Note that I've tested with:
[debugExample.C](https://gitlab.cern.ch/atlas/athena/blob/21.2/PhysicsAnalysis/AnalysisCommon/PileupReweighting/share/debugExample.C
)

and all is fine (can provide the MWE if required), so am inclined to think this is an xAH issue. I can't seem to find the issue myself, so am creating a new issue.

**Release**: AnalysisBase,21.2.22
**xAH branch**: master
**Input (MC16a)**: mc16_13TeV.361020.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ0W.deriv.DAOD_STDM4.e3569_s3126_r9364_r9315_p3523/DAOD_STDM4.13860551._000037.pool.root.1
**Relevant lines from config**:
```
c.algorithm("BasicEventSelection",    {      
  "m_name"                      : "BasicEventSelect",
  "m_applyGRLCut"               : True,
  "m_GRLxml"                    : "$WorkDir_DIR/data/DijetResonanceAlgo/grl/data17_13TeV.periodAllYear_DetStatus-v96-pro21-12_Unknown_PHYS_StandardGRL_All_Good_25ns_Triggerno17e33prim.xml",
  "m_derivationName"            : "STDM4",
  "m_useMetaData"               : False,     
  "m_storePassHLT"              : True,
  "m_applyTriggerCut"           : False,
  "m_storeTrigDecisions"        : True,      
  "m_triggerSelection"          : "HLT_.*j.*|HLT_.*mu.*|L1_.*J.*|L1_.*MU.*|HLT_.*e.*|L1_.*E.*",
  "m_checkDuplicatesData"       : False,     
  "m_applyEventCleaningCut"     : False,     
  "m_doPUreweighting"           : True,      
  "m_autoconfigPRW"             : False,
  "m_lumiCalcFileNames"         : "$WorkDir_DIR/data/DijetResonanceAlgo/lumicalc/physics_25ns_Triggerno17e33prim.lumicalc.OflLumi-13TeV-001.root",
  "m_msgLevel"                  : "Debug"    
})
```
**Crash**:
```
...
BasicEventSelection.Ba...DEBUG   in retrieve<xAOD::EventInfo_v1>(EventInfo):      Found inside xAOD::TEvent
BasicEventSelection.Ba...DEBUG   in retrieve<xAOD::EventInfo_v1>(EventInfo):      Retrieved from xAOD::TEvent
CP::TPileupReweighting... INFO    Initializing the subtool..
-1 -> -1[0,9999999] : 
284500 -> 284500[222222,324300] : 
300000 -> 300000[324300,999999] : 
CP::TPileupReweighting... INFO    Normalizing histograms and cleaning up...
CP::TPileupReweighting... INFO    ...Done
TUnixSystem::DispatchS... ERROR   segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f74ed3ff27c in waitpid () from /usr/lib64/libc.so.6
#1  0x00007f74ed382c72 in do_system () from /usr/lib64/libc.so.6
#2  0x00007f74e97103d8 in TUnixSystem::StackTrace() () from /cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBaseExternals/21.2.22/InstallArea/x86_64-slc6-gcc62-opt/bin/../lib/libCore.so
#3  0x00007f74e971288c in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBaseExternals/21.2.22/InstallArea/x86_64-slc6-gcc62-opt/bin/../lib/libCore.so
#4  <signal handler called>
#5  0x00007f74da932c60 in CP::TPileupReweighting::GetRandomRunNumber(int, double) () from /cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBase/21.2.22/InstallArea/x86_64-slc6-gcc62-opt/lib/libPileupReweightingLib.so
#6  0x00007f74da9166c2 in CP::PileupReweightingTool::apply(xAOD::EventInfo_v1 const&, bool) () from /cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBase/21.2.22/InstallArea/x86_64-slc6-gcc62-opt/lib/libPileupReweightingLib.so
#7  0x00007f74d9e28ffc in BasicEventSelection::execute (this=0x1bbfd970) at /direct/usatlas+u/vpascuzz/analysis/dijetlepton/code/source/DijetFramework/xAODAnaHelpers/Root/BasicEventSelection.cxx:745
...
```

Seems that `TPileupReweighting::GetRandomRunNumber`appears to return successfully -- comparing crash (above) to:
[TPileupReweighting.cxx#L1284](https://gitlab.cern.ch/atlas/athena/blob/21.2/PhysicsAnalysis/AnalysisCommon/PileupReweighting/Root/TPileupReweighting.cxx#L1284)

Thanks in advance,
vpascuzz.

**Comment by vpascuzz** [comment]
Thanks for following up, @kratsg.

Not yet. I've managed to make things work by providing correct PRW configs, so have stepped away from this. If I get bored (i.e. have time), I will investigate.

**Comment by kratsg** [comment]
Are you still seeing this? Reopen if so.
