### ISSUE TITLE
Can't find PathResolverFindCalibDirectory

### ISSUE THREAD

**Issue by beojan** [UCATLAS/xAODAnaHelpers#1306]
In the HH -> 4b analysis, `xAH_run.py` crashes on start with the error:
```
An exception was caught! (xAH_run.py:638)
Traceback (most recent call last):
  File "/data/atlassmallfiles/users/stanislaus/XhhCommon/build/x86_64-slc6-gcc62-opt/bin/xAH_run.py", line 386, in <module>
    path_metadata=ROOT.PathResolverFindCalibDirectory("xAODAnaHelpers/metadata")
  File "/cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBaseExternals/21.2.51/InstallArea/x86_64-slc6-gcc62-opt/lib/ROOT.py", line 613, in __getattr2
    raise AttributeError( name )
AttributeError: PathResolverFindCalibDirectory
```
It doesn't crash if xAH a346ad1d is used.
The crashing CI is here: https://gitlab.cern.ch/hh4b/XhhCommon/-/jobs/3062011

**Comment by kratsg** [comment]
Yeah, so the issue is a bit annoying. I erroneously thought `PathResolver` was just a python wrapper around the C++ code, but it seems to load in the PathResolver information as well. See:
- https://gitlab.cern.ch/atlas/athena/blob/master/Tools/PathResolver/python/__init__.py
- https://gitlab.cern.ch/atlas/athena/blob/master/Tools/PathResolver/python/PathResolver.py

**Comment by kratsg** [comment]
Specifically, this is the problem:

```
>>> import ROOT
>>> ROOT.PathResolverFindCalibDirectory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/AnalysisBaseExternals/21.2.18/InstallArea/x86_64-slc6-gcc62-opt/lib/ROOT.py", line 425, in __getattr1
    return getattr( self, name )
  File "/usr/AnalysisBaseExternals/21.2.18/InstallArea/x86_64-slc6-gcc62-opt/lib/ROOT.py", line 468, in __getattr2
    raise AttributeError( name )
AttributeError: PathResolverFindCalibDirectory
>>> ROOT.PathResolver
<class 'ROOT.PathResolver'>
>>> ROOT.PathResolverFindCalibDirectory
<ROOT.MethodProxy object at 0x7f9ffb8a1d90>
```
