### ISSUE TITLE
Bug in BasicEventSelection.cxx fileExecute()

### ISSUE THREAD

**Issue by jdandoy** [UCATLAS/xAODAnaHelpers#81]
A bug with xAODAnaHelpers-00-03-00 and AnalysisBase,2.3.12, it appears there is a crash in BasicEventSelection.cxx in fileExecute(), which causes a seg fault.  It is likely due to the recent switch of fileExecute() and histInitialize().

**Comment by kratsg** [comment]
```
Below the crash:

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x0000003d4eeac61e in waitpid () from /lib64/libc.so.6
#1  0x0000003d4ee3e609 in do_system () from /lib64/libc.so.6
#2  0x00007f3543499ecf in TUnixSystem::StackTrace() () from /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/root/6.02.05-x86_64-slc6-gcc48-opt/lib/libCore.so
#3  0x00007f354349ba3c in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/root/6.02.05-x86_64-slc6-gcc48-opt/lib/libCore.so
#4  <signal handler called>
#5  0x00007f3549f90f71 in xAOD::CutBookkeeper_v1::nAcceptedEvents() const () from /afs/cern.ch/work/j/jbossios/public/SM/new_xAODJetAnalysis/xAODUnfoldingAnalysis/41_version/RootCoreBin/lib/x86_64-slc6-gcc48-opt/libxAODCutFlow.so
#6  0x00007f354a2392fb in BasicEventSelection::fileExecute() () at /afs/cern.ch/work/j/jbossios/public/SM/new_xAODJetAnalysis/xAODUnfoldingAnalysis/41_version/xAODAnaHelpers/Root/BasicEventSelection.cxx:286
#7  0x00007f353f3d09e8 in EL::Worker::algsChangeInput() () from /afs/cern.ch/work/j/jbossios/public/SM/new_xAODJetAnalysis/xAODUnfoldingAnalysis/41_version/RootCoreBin/lib/x86_64-slc6-gcc48-opt/libEventLoop.so
#8  0x00007f353f3f30de in EL::DirectWorker::run() () from /afs/cern.ch/work/j/jbossios/public/SM/new_xAODJetAnalysis/xAODUnfoldingAnalysis/41_version/RootCoreBin/lib/x86_64-slc6-gcc48-opt/libEventLoop.so
#9  0x00007f353f3d7fe3 in EL::DirectDriver::doSubmit(EL::Job const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const () from /afs/cern.ch/work/j/jbossios/public/SM/new_xAODJetAnalysis/xAODUnfoldingAnalysis/41_version/RootCoreBin/lib/x86_64-slc6-gcc48-opt/libEventLoop.so
#10 0x00007f353f3e8453 in EL::Driver::submitOnly(EL::Job const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const () from /afs/cern.ch/work/j/jbossios/public/SM/new_xAODJetAnalysis/xAODUnfoldingAnalysis/41_version/RootCoreBin/lib/x86_64-slc6-gcc48-opt/libEventLoop.so
#11 0x00007f353f3e8de9 in EL::Driver::submit(EL::Job const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const () from /afs/cern.ch/work/j/jbossios/public/SM/new_xAODJetAnalysis/xAODUnfoldingAnalysis/41_version/RootCoreBin/lib/x86_64-slc6-gcc48-opt/libEventLoop.so
#12 0x0000000000403aea in main () at /afs/cern.ch/work/j/jbossios/public/SM/new_xAODJetAnalysis/xAODUnfoldingAnalysis/41_version/UnfoldingAnalysis/util/RunUnfolding.cxx:149
===========================================================
```

**Comment by kratsg** [comment]
Most likely related to #77

**Comment by kratsg** [comment]
I can't seem to reproduce this issue

```
git clone git@github.com:UCATLAS/xAODAnaHelpers && cd xAODAnaHelpers && git checkout -b 00-03-01 00-03-01 && cd ../
python xAODAnaHelpers/scripts/checkoutASGtags.py 2.3.12
rc find_packages
rc compile
test_multiAlgo submitDir/ /share/t3data3/kratsg/xAODs/ mc15_13TeV.410000.PowhegPythiaEvtGen_P2012_ttbar_hdamp172p5_nonallhad.merge.AOD.e3698_s2608_s2183_r6630_r6264_tid05419191_00/ AOD.05419191._000003.pool.root.1 
```

```
Info in <OverlapRemover::OverlapRemover()>: Calling constructor
Running sample: mc15_13TeV.410000.PowhegPythiaEvtGen_P2012_ttbar_hdamp172p5_nonallhad.merge.AOD.e3698_s2608_s2183_r6630_r6264_tid05419191_00
Info in <BasicEventSelection::histInitialize()>: Calling histInitialize
Debug:                    False                          [Local]
GRL:                      $ROOTCOREBIN/data/xAODAnaHelpers/data12_8TeV.periodAllYear_DetStatus-v61-pro14-02_DQDefects-00-01-00_PHYS_StandardGRL_All_Good.xml [Local]
DoPileupReweighting:      False                          [Local]
VertexContainer:          PrimaryVertices                [Local]
NTrackForPrimaryVertex:   2                              [Local]
TruthLevelOnly:           False                          [Local]
DerivationName:           HIGG3D1                        [Local]
Info in <BasicEventSelection::configure()>: BasicEventSelection succesfully configured! 
Info in <BasicEventSelection::histInitialize()>: Histograms initialized!
Info in <MuonSelector::histInitialize()>: Calling histInitialize
Info in <ElectronSelector::histInitialize()>: Calling histInitialize
Info in <JetSelector::histInitialize()>: Calling histInitialize
Info in <JetSelector::histInitialize()>: Calling histInitialize
Info in <JetHistsAlgo::histInitialize()>: jetHistsAlgo_signal
Info in <JetHistsAlgo::histInitialize()>: jetHistsAlgo_btag
Info in <JetSelector::histInitialize()>: Calling histInitialize
Info in <JetHistsAlgo::histInitialize()>: jetHistsAlgo_truth
Info in <JetHistsAlgo::histInitialize()>: AntiKt10/
Warning in <xAOD::TEvent::initStats>: Couldn't find dictionary for type "DataVector<xAOD::TrackParticleClusterAssociation_v1>"
Info in <BasicEventSelection::fileExecute()>: Calling fileExecute
Info in <BasicEventSelection::histInitialize()>: Meta data from this file:
Info in <BasicEventSelection::histInitialize()>: Initial  events	 = 2576980377
Info in <BasicEventSelection::histInitialize()>: Selected events	 = 2576980377
Info in <BasicEventSelection::histInitialize()>: Initial  sum of weights = -0.000000
Info in <BasicEventSelection::histInitialize()>: Selected sum of weights = -0.000000
Info in <BasicEventSelection::histInitialize()>: Initial  sum of weights squared = -0.000000
Info in <BasicEventSelection::histInitialize()>: Selected sum of weights squared = -0.000000
Info in <MuonSelector::fileExecute()>: Calling fileExecute
Info in <ElectronSelector::fileExecute()>: Calling fileExecute
Info in <JetSelector::fileExecute()>: Calling fileExecute
Info in <JetSelector::fileExecute()>: Calling fileExecute
Info in <JetSelector::fileExecute()>: Calling fileExecute
Warning in <xAOD::TEvent::initStats>: Couldn't find dictionary for type "DataVector<xAOD::TrackParticleClusterAssociation_v1>"
Info in <MuonSelector::changeInput()>: Calling changeInput
Info in <ElectronSelector::changeInput()>: Calling changeInput
Info in <JetSelector::changeInput()>: Calling changeInput
```

**Comment by jdandoy** [comment]
This is due to a known issue with DAODs.  Run with UseMetaData False for now.
